/**
 * Shan Truong, Aryan Verma, Jerry Wu
 * June 11, 2024
 * Collision program that displays linear (1D) collisions from user inputs
 * User selects the 2 masses, velocities, and type of collision (perfectly elastic, partially elastic or completely inelastic)
 * The user can look up collision related terms (physics terms)
 * The user can look at the instructions to see how the program is supposed to be operated 
 * The user can look at the credits on who created the program
 * The user can exit the program
 */
package collisionvisualizer;

//imports
import java.awt.Dimension;

/**
 * The main page of the Collision Visualizer application. This class provides the
 * main interface with buttons to navigate to different sections of the application,
 * including simulation, instructions, and definitions.
 * It also includes an option to exit the application.
 *
 */
public class MainPage extends javax.swing.JFrame {

    //private attribute for instructions page
    private InstructionPage instructionsWindow;
    
    //private attribute for simulation page
    private SimulationPage simulationWindow;
    
    //private attribute for definitions page
    private DefinitionPage definitionWindow;
    
    //private attribute for credit page
    private CreditsPage creditWindow;

    /**
     * Creates new form MainPage and initializes the components.
     */
    public MainPage() {
        
        //displaying GUI
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        simulationBtn = new javax.swing.JButton();
        instructionBtn = new javax.swing.JButton();
        defBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        creditBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(253, 251, 196));

        titleLbl.setFont(new java.awt.Font("Heyam", 0, 48)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Collision Visualizer");

        simulationBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        simulationBtn.setText("Enter Simulation");
        simulationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulationBtnActionPerformed(evt);
            }
        });

        instructionBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        instructionBtn.setText("Instructions");
        instructionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionBtnActionPerformed(evt);
            }
        });

        defBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        defBtn.setText("Definitions");
        defBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("By Aryan V, Shan T, Jerry W");

        creditBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        creditBtn.setText("Credits");
        creditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(titleLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(simulationBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                            .addComponent(instructionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(defBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(creditBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel1)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(simulationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(instructionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(defBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(creditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Handles the action of the Definitions button, opening the Definitions window.
     * @param evt - The action event
     */
    private void defBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defBtnActionPerformed
        
        //if the definition attribute is null
        if (definitionWindow == null) {
            
            //swaping pages
            definitionWindow = new DefinitionPage(this);
        }

        //displaying new page
        definitionWindow.setVisible(true);
        
        //removing menu page visibility 
        this.setVisible(false);
    }//GEN-LAST:event_defBtnActionPerformed
    
    /**
     * Handles the action of the Instructions button, opening the Instructions window.
     * @param evt - The action event
     */
    private void instructionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionBtnActionPerformed
        
        //if the instructions attribute is null
        if (instructionsWindow == null) {
            
            //swaping pages
            instructionsWindow = new InstructionPage(this);
        }

        //displaying new page
        instructionsWindow.setVisible(true);
        
        //removing menu page visibility 
        this.setVisible(false);
    }//GEN-LAST:event_instructionBtnActionPerformed
    
    /**
     * Handles the action of the Simulation button, opening the Simulation window.
     * @param evt - The action event
     */
    private void simulationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulationBtnActionPerformed
        
        //if the simulation attribute is null
        if (simulationWindow == null) {
            
            //swaping pages
            simulationWindow = new SimulationPage(this);
        }

        //displaying new page
        simulationWindow.setVisible(true);
        
        //removing menu page visibility 
        this.setVisible(false);
    }//GEN-LAST:event_simulationBtnActionPerformed
    
    /**
     * Handles the action of the Exit button, closing the application.
     * @param evt - The action event
     */
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        
        //exit program
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * Handles the action of the credit button, opening the credit window.
     * @param evt - The action event
     */
    private void creditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditBtnActionPerformed
        
        //if the credit attribute is null
        if (creditWindow == null) {
             
             //swaping pages
            creditWindow = new CreditsPage(this);
        }

         //displaying new page
        creditWindow.setVisible(true);
        
        //removing menu page visibility 
        this.setVisible(false);
    }//GEN-LAST:event_creditBtnActionPerformed

    /**
     * The main method to run the MainPage form.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                //displaying main page
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creditBtn;
    private javax.swing.JButton defBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton instructionBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton simulationBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables

    /**
     * Method to set size of windows
     * @param length - length of the window 
     * @param width - width of the window
     */
    private void setPreferredSize(int length, int width) {
        
        //setting preffered size of window 
        setPreferredSize(new Dimension(length, width));
    }

}
